2024-11-19T15:05:39.273751-+08:00 | DESKTOP-31GR1E6 | 23792  | api-server | INFO     | werkzeug:_internal.py:97 | [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5001
 * Running on http://192.168.99.88:5001
2024-11-19T15:05:39.356850-+08:00 | DESKTOP-31GR1E6 | 23792  | api-server | INFO     | werkzeug:_internal.py:97 | [33mPress CTRL+C to quit[0m
2024-11-19T15:05:47.861712-+08:00 | DESKTOP-31GR1E6 | 23792  | api-server | INFO     | root:api_server.py:78 |  "/api/ai/scale/analyzer POST"
2024-11-19T15:05:47.874368-+08:00 | DESKTOP-31GR1E6 | 23792  | api-server | INFO     | root:api_server.py:18 | Í¼Æ¬µØÖ·: E:/electronic_scale/test1.png
2024-11-19T15:05:47.975152-+08:00 | DESKTOP-31GR1E6 | 23792  | api-server | ERROR    | root:inference.py:136 | ÎÞ·¨½âÂëÍ¼Æ¬
2024-11-19T15:05:47.976152-+08:00 | DESKTOP-31GR1E6 | 23792  | api-server | INFO     | root:api_server.py:65 | ½Ó¿Ú·µ»ØÖµÎª£º{'code': 200, 'result': None, 'msg': 'ÍÆÀí½á¹û²»ºÏ·¨'}
2024-11-19T15:05:47.976152-+08:00 | DESKTOP-31GR1E6 | 23792  | api-server | INFO     | root:api_server.py:66 | ½Ó¿ÚºÄÊ±: 0.10 Ãë
2024-11-19T15:05:47.977152-+08:00 | DESKTOP-31GR1E6 | 23792  | api-server | INFO     | werkzeug:_internal.py:97 | 192.168.99.88 - - [19/Nov/2024 15:05:47] "POST /api/ai/scale/analyzer HTTP/1.1" 200 -
2024-11-19T15:06:29.275604-+08:00 | DESKTOP-31GR1E6 | 24704  | api-server | INFO     | werkzeug:_internal.py:97 | [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5001
 * Running on http://192.168.99.88:5001
2024-11-19T15:06:29.276601-+08:00 | DESKTOP-31GR1E6 | 24704  | api-server | INFO     | werkzeug:_internal.py:97 | [33mPress CTRL+C to quit[0m
2024-11-19T15:06:32.300571-+08:00 | DESKTOP-31GR1E6 | 24704  | api-server | INFO     | root:api_server.py:78 |  "/api/ai/scale/analyzer POST"
2024-11-19T15:06:32.300571-+08:00 | DESKTOP-31GR1E6 | 24704  | api-server | INFO     | root:api_server.py:18 | Í¼Æ¬µØÖ·: E:/electronic_scale/test1.png
2024-11-19T15:06:46.324045-+08:00 | DESKTOP-31GR1E6 | 24704  | api-server | INFO     | werkzeug:_internal.py:97 | 192.168.99.88 - - [19/Nov/2024 15:06:46] "POST /api/ai/scale/analyzer HTTP/1.1" 200 -
2024-11-19T15:07:24.071075-+08:00 | DESKTOP-31GR1E6 | 24704  | api-server | INFO     | werkzeug:_internal.py:97 | 192.168.99.88 - - [19/Nov/2024 15:07:24] "POST /api/ai/scale/analyzer HTTP/1.1" 200 -
2024-11-19T16:05:21.814730-+08:00 | DESKTOP-31GR1E6 | 9636   | api-server | INFO     | werkzeug:_internal.py:97 | [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5001
 * Running on http://192.168.99.88:5001
2024-11-19T16:05:21.814730-+08:00 | DESKTOP-31GR1E6 | 9636   | api-server | INFO     | werkzeug:_internal.py:97 | [33mPress CTRL+C to quit[0m
2024-11-19T16:07:53.283187-+08:00 | DESKTOP-31GR1E6 | 9636   | api-server | INFO     | root:api_server.py:78 |  "/api/ai/scale/analyzer POST"
2024-11-19T16:07:53.286191-+08:00 | DESKTOP-31GR1E6 | 9636   | api-server | INFO     | root:api_server.py:18 | Í¼Æ¬µØÖ·: E:/electronic_scale/test3.png
2024-11-19T16:07:53.294257-+08:00 | DESKTOP-31GR1E6 | 9636   | api-server | ERROR    | root:api_server.py:62 | ÍÆÀí´íÎó: inference() missing 1 required positional argument: 'template_path'
Traceback (most recent call last):
  File "E:\electronic_scale\api_server.py", line 40, in post
    scale_result = inference(encoded_url)  # Ê¹ÓÃ±àÂëºóµÄ URL ½øÐÐÍÆÀí
TypeError: inference() missing 1 required positional argument: 'template_path'
2024-11-19T16:07:53.296279-+08:00 | DESKTOP-31GR1E6 | 9636   | api-server | INFO     | root:api_server.py:65 | ½Ó¿Ú·µ»ØÖµÎª£º{'code': 200, 'result': None, 'msg': 'ÍÆÀí´íÎó'}
2024-11-19T16:07:53.297291-+08:00 | DESKTOP-31GR1E6 | 9636   | api-server | INFO     | root:api_server.py:66 | ½Ó¿ÚºÄÊ±: 0.00 Ãë
2024-11-19T16:07:53.299252-+08:00 | DESKTOP-31GR1E6 | 9636   | api-server | INFO     | werkzeug:_internal.py:97 | 192.168.99.88 - - [19/Nov/2024 16:07:53] "POST /api/ai/scale/analyzer HTTP/1.1" 200 -
2024-11-19T16:09:46.822453-+08:00 | DESKTOP-31GR1E6 | 26320  | api-server | INFO     | werkzeug:_internal.py:97 | [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5001
 * Running on http://192.168.99.88:5001
2024-11-19T16:09:46.822453-+08:00 | DESKTOP-31GR1E6 | 26320  | api-server | INFO     | werkzeug:_internal.py:97 | [33mPress CTRL+C to quit[0m
2024-11-19T16:09:50.014650-+08:00 | DESKTOP-31GR1E6 | 26320  | api-server | INFO     | root:api_server.py:79 |  "/api/ai/scale/analyzer POST"
2024-11-19T16:09:50.014650-+08:00 | DESKTOP-31GR1E6 | 26320  | api-server | INFO     | root:api_server.py:19 | Í¼Æ¬µØÖ·: E:/electronic_scale/test3.png
2024-11-19T16:09:50.014650-+08:00 | DESKTOP-31GR1E6 | 26320  | api-server | ERROR    | root:api_server.py:63 | ÍÆÀí´íÎó: inference() missing 1 required positional argument: 'template_path'
Traceback (most recent call last):
  File "E:\electronic_scale\api_server.py", line 41, in post
    scale_result = inference(encoded_url)
TypeError: inference() missing 1 required positional argument: 'template_path'
2024-11-19T16:09:50.015651-+08:00 | DESKTOP-31GR1E6 | 26320  | api-server | INFO     | root:api_server.py:66 | ½Ó¿Ú·µ»ØÖµÎª£º{'code': 200, 'result': None, 'msg': 'ÍÆÀí´íÎó'}
2024-11-19T16:09:50.015651-+08:00 | DESKTOP-31GR1E6 | 26320  | api-server | INFO     | root:api_server.py:67 | ½Ó¿ÚºÄÊ±: 0.00 Ãë
2024-11-19T16:09:50.016650-+08:00 | DESKTOP-31GR1E6 | 26320  | api-server | INFO     | werkzeug:_internal.py:97 | 192.168.99.88 - - [19/Nov/2024 16:09:50] "POST /api/ai/scale/analyzer HTTP/1.1" 200 -
2024-11-19T16:14:29.299809-+08:00 | DESKTOP-31GR1E6 | 24868  | api-server | INFO     | werkzeug:_internal.py:97 | [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5001
 * Running on http://192.168.99.88:5001
2024-11-19T16:14:29.299809-+08:00 | DESKTOP-31GR1E6 | 24868  | api-server | INFO     | werkzeug:_internal.py:97 | [33mPress CTRL+C to quit[0m
2024-11-19T16:14:48.397175-+08:00 | DESKTOP-31GR1E6 | 24868  | api-server | INFO     | root:api_server.py:68 |  "/api/ai/scale/analyzer POST"
2024-11-19T16:14:48.397175-+08:00 | DESKTOP-31GR1E6 | 24868  | api-server | INFO     | root:api_server.py:16 | Í¼Æ¬µØÖ·: E:/electronic_scale/test3.png
2024-11-19T16:14:48.398176-+08:00 | DESKTOP-31GR1E6 | 24868  | api-server | INFO     | root:api_server.py:55 | ½Ó¿Ú·µ»ØÖµÎª£º{'code': 200, 'result': None, 'msg': 'ÍÆÀí½á¹û²»ºÏ·¨'}
2024-11-19T16:14:48.398176-+08:00 | DESKTOP-31GR1E6 | 24868  | api-server | INFO     | root:api_server.py:56 | ½Ó¿ÚºÄÊ±: 0.00 Ãë
2024-11-19T16:14:48.398176-+08:00 | DESKTOP-31GR1E6 | 24868  | api-server | INFO     | werkzeug:_internal.py:97 | 192.168.99.88 - - [19/Nov/2024 16:14:48] "POST /api/ai/scale/analyzer HTTP/1.1" 200 -
2024-11-19T16:16:52.162011-+08:00 | DESKTOP-31GR1E6 | 20524  | api-server | INFO     | werkzeug:_internal.py:97 | [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5001
 * Running on http://192.168.99.88:5001
2024-11-19T16:16:52.162011-+08:00 | DESKTOP-31GR1E6 | 20524  | api-server | INFO     | werkzeug:_internal.py:97 | [33mPress CTRL+C to quit[0m
2024-11-19T16:16:55.534251-+08:00 | DESKTOP-31GR1E6 | 20524  | api-server | INFO     | root:api_server.py:70 |  "/api/ai/scale/analyzer POST"
2024-11-19T16:16:55.534251-+08:00 | DESKTOP-31GR1E6 | 20524  | api-server | INFO     | root:api_server.py:16 | Í¼Æ¬µØÖ·: E:/electronic_scale/test3.png
2024-11-19T16:16:55.535252-+08:00 | DESKTOP-31GR1E6 | 20524  | api-server | ERROR    | root:api_server.py:54 | ÍÆÀí´íÎó: unsupported operand type(s) for +: 'NoneType' and 'str'
Traceback (most recent call last):
  File "E:\electronic_scale\api_server.py", line 51, in post
    print(scale_result + "2")
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
2024-11-19T16:16:55.536253-+08:00 | DESKTOP-31GR1E6 | 20524  | api-server | INFO     | root:api_server.py:57 | ½Ó¿Ú·µ»ØÖµÎª£º{'code': 200, 'result': None, 'msg': 'ÍÆÀí´íÎó'}
2024-11-19T16:16:55.536253-+08:00 | DESKTOP-31GR1E6 | 20524  | api-server | INFO     | root:api_server.py:58 | ½Ó¿ÚºÄÊ±: 0.00 Ãë
2024-11-19T16:16:55.537254-+08:00 | DESKTOP-31GR1E6 | 20524  | api-server | INFO     | werkzeug:_internal.py:97 | 192.168.99.88 - - [19/Nov/2024 16:16:55] "POST /api/ai/scale/analyzer HTTP/1.1" 200 -
2024-11-19T16:17:42.545339-+08:00 | DESKTOP-31GR1E6 | 25436  | api-server | INFO     | werkzeug:_internal.py:97 | [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5001
 * Running on http://192.168.99.88:5001
2024-11-19T16:17:42.545339-+08:00 | DESKTOP-31GR1E6 | 25436  | api-server | INFO     | werkzeug:_internal.py:97 | [33mPress CTRL+C to quit[0m
2024-11-19T16:17:46.643607-+08:00 | DESKTOP-31GR1E6 | 25436  | api-server | INFO     | root:api_server.py:70 |  "/api/ai/scale/analyzer POST"
2024-11-19T16:17:46.644609-+08:00 | DESKTOP-31GR1E6 | 25436  | api-server | INFO     | root:api_server.py:16 | Í¼Æ¬µØÖ·: E:/electronic_scale/test3.png
2024-11-19T16:17:46.647604-+08:00 | DESKTOP-31GR1E6 | 25436  | api-server | ERROR    | root:api_server.py:54 | ÍÆÀí´íÎó: unsupported operand type(s) for +: 'NoneType' and 'str'
Traceback (most recent call last):
  File "E:\electronic_scale\api_server.py", line 51, in post
    print(scale_result + "2")
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
2024-11-19T16:17:46.649606-+08:00 | DESKTOP-31GR1E6 | 25436  | api-server | INFO     | root:api_server.py:57 | ½Ó¿Ú·µ»ØÖµÎª£º{'code': 200, 'result': None, 'msg': 'ÍÆÀí´íÎó'}
2024-11-19T16:17:46.649606-+08:00 | DESKTOP-31GR1E6 | 25436  | api-server | INFO     | root:api_server.py:58 | ½Ó¿ÚºÄÊ±: 0.00 Ãë
2024-11-19T16:17:46.650605-+08:00 | DESKTOP-31GR1E6 | 25436  | api-server | INFO     | werkzeug:_internal.py:97 | 192.168.99.88 - - [19/Nov/2024 16:17:46] "POST /api/ai/scale/analyzer HTTP/1.1" 200 -
2024-11-19T16:18:39.462041-+08:00 | DESKTOP-31GR1E6 | 13428  | api-server | INFO     | werkzeug:_internal.py:97 | [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5001
 * Running on http://192.168.99.88:5001
2024-11-19T16:18:39.462041-+08:00 | DESKTOP-31GR1E6 | 13428  | api-server | INFO     | werkzeug:_internal.py:97 | [33mPress CTRL+C to quit[0m
2024-11-19T16:19:06.395831-+08:00 | DESKTOP-31GR1E6 | 22196  | api-server | INFO     | werkzeug:_internal.py:97 | [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5001
 * Running on http://192.168.99.88:5001
2024-11-19T16:19:06.396828-+08:00 | DESKTOP-31GR1E6 | 22196  | api-server | INFO     | werkzeug:_internal.py:97 | [33mPress CTRL+C to quit[0m
2024-11-19T16:19:08.502211-+08:00 | DESKTOP-31GR1E6 | 22196  | api-server | INFO     | root:api_server.py:70 |  "/api/ai/scale/analyzer POST"
2024-11-19T16:19:08.502211-+08:00 | DESKTOP-31GR1E6 | 22196  | api-server | INFO     | root:api_server.py:16 | Í¼Æ¬µØÖ·: E:/electronic_scale/test3.png
2024-11-19T16:19:08.503210-+08:00 | DESKTOP-31GR1E6 | 22196  | api-server | INFO     | root:api_server.py:57 | ½Ó¿Ú·µ»ØÖµÎª£º{'code': 200, 'result': None, 'msg': 'ÍÆÀí½á¹û²»ºÏ·¨'}
2024-11-19T16:19:08.503210-+08:00 | DESKTOP-31GR1E6 | 22196  | api-server | INFO     | root:api_server.py:58 | ½Ó¿ÚºÄÊ±: 0.00 Ãë
2024-11-19T16:19:08.503210-+08:00 | DESKTOP-31GR1E6 | 22196  | api-server | INFO     | werkzeug:_internal.py:97 | 192.168.99.88 - - [19/Nov/2024 16:19:08] "POST /api/ai/scale/analyzer HTTP/1.1" 200 -
2024-11-19T16:24:09.054882-+08:00 | DESKTOP-31GR1E6 | 19944  | api-server | INFO     | werkzeug:_internal.py:97 | [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5001
 * Running on http://192.168.99.88:5001
2024-11-19T16:24:09.054882-+08:00 | DESKTOP-31GR1E6 | 19944  | api-server | INFO     | werkzeug:_internal.py:97 | [33mPress CTRL+C to quit[0m
2024-11-19T16:24:20.419058-+08:00 | DESKTOP-31GR1E6 | 19944  | api-server | INFO     | root:api_server.py:70 |  "/api/ai/scale/analyzer POST"
2024-11-19T16:24:20.420059-+08:00 | DESKTOP-31GR1E6 | 19944  | api-server | INFO     | root:api_server.py:16 | Í¼Æ¬µØÖ·: E:/electronic_scale/test3.png
2024-11-19T16:24:20.420059-+08:00 | DESKTOP-31GR1E6 | 19944  | api-server | ERROR    | root:api_server.py:26 | ²ÎÊý´íÎó: inference() got an unexpected keyword argument 'template_path'
Traceback (most recent call last):
  File "E:\electronic_scale\api_server.py", line 23, in post
    scale_result = inference(pict_url, template_path=pict_url)  # Ê¹ÓÃ±¾µØÂ·¾¶×÷ÎªÄ£°åÂ·¾¶
TypeError: inference() got an unexpected keyword argument 'template_path'
2024-11-19T16:24:20.421059-+08:00 | DESKTOP-31GR1E6 | 19944  | api-server | INFO     | werkzeug:_internal.py:97 | 192.168.99.88 - - [19/Nov/2024 16:24:20] "[31m[1mPOST /api/ai/scale/analyzer HTTP/1.1[0m" 400 -
2024-11-19T16:38:07.513496-+08:00 | DESKTOP-31GR1E6 | 15112  | api-server | INFO     | werkzeug:_internal.py:97 | [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5001
 * Running on http://192.168.99.88:5001
2024-11-19T16:38:07.513496-+08:00 | DESKTOP-31GR1E6 | 15112  | api-server | INFO     | werkzeug:_internal.py:97 | [33mPress CTRL+C to quit[0m
2024-11-19T16:38:11.779434-+08:00 | DESKTOP-31GR1E6 | 19944  | api-server | INFO     | root:api_server.py:70 |  "/api/ai/scale/analyzer POST"
2024-11-19T16:38:11.797888-+08:00 | DESKTOP-31GR1E6 | 19944  | api-server | INFO     | root:api_server.py:16 | Í¼Æ¬µØÖ·: E:/electronic_scale/test3.png
2024-11-19T16:38:11.797888-+08:00 | DESKTOP-31GR1E6 | 19944  | api-server | ERROR    | root:api_server.py:26 | ²ÎÊý´íÎó: inference() got an unexpected keyword argument 'template_path'
Traceback (most recent call last):
  File "E:\electronic_scale\api_server.py", line 23, in post
    # µ÷ÓÃ inference º¯Êý½øÐÐÍÆÀí£¬´«ÈëÍ¼Æ¬Â·¾¶
TypeError: inference() got an unexpected keyword argument 'template_path'
2024-11-19T16:38:11.800884-+08:00 | DESKTOP-31GR1E6 | 19944  | api-server | INFO     | werkzeug:_internal.py:97 | 192.168.99.88 - - [19/Nov/2024 16:38:11] "[31m[1mPOST /api/ai/scale/analyzer HTTP/1.1[0m" 400 -
2024-11-19T16:38:28.436898-+08:00 | DESKTOP-31GR1E6 | 19944  | api-server | INFO     | root:api_server.py:70 |  "/api/ai/scale/analyzer POST"
2024-11-19T16:38:28.437894-+08:00 | DESKTOP-31GR1E6 | 19944  | api-server | INFO     | root:api_server.py:16 | Í¼Æ¬µØÖ·: E:/electronic_scale/test3.png
2024-11-19T16:38:28.437894-+08:00 | DESKTOP-31GR1E6 | 19944  | api-server | ERROR    | root:api_server.py:26 | ²ÎÊý´íÎó: inference() got an unexpected keyword argument 'template_path'
Traceback (most recent call last):
  File "E:\electronic_scale\api_server.py", line 23, in post
    # µ÷ÓÃ inference º¯Êý½øÐÐÍÆÀí£¬´«ÈëÍ¼Æ¬Â·¾¶
TypeError: inference() got an unexpected keyword argument 'template_path'
2024-11-19T16:38:28.439893-+08:00 | DESKTOP-31GR1E6 | 19944  | api-server | INFO     | werkzeug:_internal.py:97 | 192.168.99.88 - - [19/Nov/2024 16:38:28] "[31m[1mPOST /api/ai/scale/analyzer HTTP/1.1[0m" 400 -
2024-11-19T16:39:12.670074-+08:00 | DESKTOP-31GR1E6 | 20752  | api-server | INFO     | werkzeug:_internal.py:97 | [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5001
 * Running on http://192.168.99.88:5001
2024-11-19T16:39:12.670074-+08:00 | DESKTOP-31GR1E6 | 20752  | api-server | INFO     | werkzeug:_internal.py:97 | [33mPress CTRL+C to quit[0m
2024-11-19T16:39:22.767631-+08:00 | DESKTOP-31GR1E6 | 19944  | api-server | INFO     | root:api_server.py:70 |  "/api/ai/scale/analyzer POST"
2024-11-19T16:39:22.768630-+08:00 | DESKTOP-31GR1E6 | 19944  | api-server | INFO     | root:api_server.py:16 | Í¼Æ¬µØÖ·: E:/electronic_scale/test3.png
2024-11-19T16:39:22.768630-+08:00 | DESKTOP-31GR1E6 | 19944  | api-server | ERROR    | root:api_server.py:26 | ²ÎÊý´íÎó: inference() got an unexpected keyword argument 'template_path'
Traceback (most recent call last):
  File "E:\electronic_scale\api_server.py", line 23, in post
    # µ÷ÓÃ inference º¯Êý½øÐÐÍÆÀí£¬´«ÈëÍ¼Æ¬Â·¾¶
TypeError: inference() got an unexpected keyword argument 'template_path'
2024-11-19T16:39:22.768630-+08:00 | DESKTOP-31GR1E6 | 19944  | api-server | INFO     | werkzeug:_internal.py:97 | 192.168.99.88 - - [19/Nov/2024 16:39:22] "[31m[1mPOST /api/ai/scale/analyzer HTTP/1.1[0m" 400 -
2024-11-19T16:41:23.874221-+08:00 | DESKTOP-31GR1E6 | 22680  | api-server | INFO     | werkzeug:_internal.py:97 | [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5001
 * Running on http://192.168.99.88:5001
2024-11-19T16:41:23.875190-+08:00 | DESKTOP-31GR1E6 | 22680  | api-server | INFO     | werkzeug:_internal.py:97 | [33mPress CTRL+C to quit[0m
2024-11-19T16:41:33.351018-+08:00 | DESKTOP-31GR1E6 | 19944  | api-server | INFO     | root:api_server.py:70 |  "/api/ai/scale/analyzer POST"
2024-11-19T16:41:33.352018-+08:00 | DESKTOP-31GR1E6 | 19944  | api-server | INFO     | root:api_server.py:16 | Í¼Æ¬µØÖ·: E:/electronic_scale/test3.png
2024-11-19T16:41:33.352018-+08:00 | DESKTOP-31GR1E6 | 19944  | api-server | ERROR    | root:api_server.py:26 | ²ÎÊý´íÎó: inference() got an unexpected keyword argument 'template_path'
Traceback (most recent call last):
  File "E:\electronic_scale\api_server.py", line 23, in post
    # µ÷ÓÃ inference º¯Êý½øÐÐÍÆÀí£¬´«ÈëÍ¼Æ¬Â·¾¶
TypeError: inference() got an unexpected keyword argument 'template_path'
2024-11-19T16:41:33.353019-+08:00 | DESKTOP-31GR1E6 | 19944  | api-server | INFO     | werkzeug:_internal.py:97 | 192.168.99.88 - - [19/Nov/2024 16:41:33] "[31m[1mPOST /api/ai/scale/analyzer HTTP/1.1[0m" 400 -
2024-11-19T16:41:35.491792-+08:00 | DESKTOP-31GR1E6 | 19944  | api-server | INFO     | root:api_server.py:70 |  "/api/ai/scale/analyzer POST"
2024-11-19T16:41:35.491792-+08:00 | DESKTOP-31GR1E6 | 19944  | api-server | INFO     | root:api_server.py:16 | Í¼Æ¬µØÖ·: E:/electronic_scale/test3.png
2024-11-19T16:41:35.492793-+08:00 | DESKTOP-31GR1E6 | 19944  | api-server | ERROR    | root:api_server.py:26 | ²ÎÊý´íÎó: inference() got an unexpected keyword argument 'template_path'
Traceback (most recent call last):
  File "E:\electronic_scale\api_server.py", line 23, in post
    # µ÷ÓÃ inference º¯Êý½øÐÐÍÆÀí£¬´«ÈëÍ¼Æ¬Â·¾¶
TypeError: inference() got an unexpected keyword argument 'template_path'
2024-11-19T16:41:35.494796-+08:00 | DESKTOP-31GR1E6 | 19944  | api-server | INFO     | werkzeug:_internal.py:97 | 192.168.99.88 - - [19/Nov/2024 16:41:35] "[31m[1mPOST /api/ai/scale/analyzer HTTP/1.1[0m" 400 -
2024-11-19T16:44:11.841065-+08:00 | DESKTOP-31GR1E6 | 27636  | api-server | INFO     | werkzeug:_internal.py:97 | [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5001
 * Running on http://192.168.99.88:5001
2024-11-19T16:44:11.841065-+08:00 | DESKTOP-31GR1E6 | 27636  | api-server | INFO     | werkzeug:_internal.py:97 | [33mPress CTRL+C to quit[0m
2024-11-19T16:44:18.996464-+08:00 | DESKTOP-31GR1E6 | 19944  | api-server | INFO     | root:api_server.py:70 |  "/api/ai/scale/analyzer POST"
2024-11-19T16:44:18.997463-+08:00 | DESKTOP-31GR1E6 | 19944  | api-server | INFO     | root:api_server.py:16 | Í¼Æ¬µØÖ·: E:/electronic_scale/test3.png
2024-11-19T16:44:18.997463-+08:00 | DESKTOP-31GR1E6 | 19944  | api-server | ERROR    | root:api_server.py:26 | ²ÎÊý´íÎó: inference() got an unexpected keyword argument 'template_path'
Traceback (most recent call last):
  File "E:\electronic_scale\api_server.py", line 23, in post
    # ¼ì²éÍ¼Æ¬Â·¾¶ÊÇ·ñÓÐÐ§
TypeError: inference() got an unexpected keyword argument 'template_path'
2024-11-19T16:44:18.998463-+08:00 | DESKTOP-31GR1E6 | 19944  | api-server | INFO     | werkzeug:_internal.py:97 | 192.168.99.88 - - [19/Nov/2024 16:44:18] "[31m[1mPOST /api/ai/scale/analyzer HTTP/1.1[0m" 400 -
2024-11-19T16:51:27.901915-+08:00 | DESKTOP-31GR1E6 | 26588  | api-server | INFO     | werkzeug:_internal.py:97 | [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5001
 * Running on http://192.168.99.88:5001
2024-11-19T16:51:27.901915-+08:00 | DESKTOP-31GR1E6 | 26588  | api-server | INFO     | werkzeug:_internal.py:97 | [33mPress CTRL+C to quit[0m
2024-11-19T16:52:30.997311-+08:00 | DESKTOP-31GR1E6 | 19944  | api-server | INFO     | root:api_server.py:70 |  "/api/ai/scale/analyzer POST"
2024-11-19T16:52:30.997311-+08:00 | DESKTOP-31GR1E6 | 19944  | api-server | INFO     | root:api_server.py:16 | Í¼Æ¬µØÖ·: E:/electronic_scale/test3.png
2024-11-19T16:52:30.997311-+08:00 | DESKTOP-31GR1E6 | 19944  | api-server | ERROR    | root:api_server.py:26 | ²ÎÊý´íÎó: inference() got an unexpected keyword argument 'template_path'
Traceback (most recent call last):
  File "E:\electronic_scale\api_server.py", line 23, in post
TypeError: inference() got an unexpected keyword argument 'template_path'
2024-11-19T16:52:30.998312-+08:00 | DESKTOP-31GR1E6 | 19944  | api-server | INFO     | werkzeug:_internal.py:97 | 192.168.99.88 - - [19/Nov/2024 16:52:30] "[31m[1mPOST /api/ai/scale/analyzer HTTP/1.1[0m" 400 -
2024-11-19T16:52:54.477173-+08:00 | DESKTOP-31GR1E6 | 19944  | api-server | INFO     | root:api_server.py:70 |  "/api/ai/scale/analyzer POST"
2024-11-19T16:52:54.478192-+08:00 | DESKTOP-31GR1E6 | 19944  | api-server | INFO     | root:api_server.py:16 | Í¼Æ¬µØÖ·: E:/electronic_scale/test3.png
2024-11-19T16:52:54.479188-+08:00 | DESKTOP-31GR1E6 | 19944  | api-server | ERROR    | root:api_server.py:26 | ²ÎÊý´íÎó: inference() got an unexpected keyword argument 'template_path'
Traceback (most recent call last):
  File "E:\electronic_scale\api_server.py", line 23, in post
TypeError: inference() got an unexpected keyword argument 'template_path'
2024-11-19T16:52:54.480191-+08:00 | DESKTOP-31GR1E6 | 19944  | api-server | INFO     | werkzeug:_internal.py:97 | 192.168.99.88 - - [19/Nov/2024 16:52:54] "[31m[1mPOST /api/ai/scale/analyzer HTTP/1.1[0m" 400 -
2024-11-19T16:54:04.427497-+08:00 | DESKTOP-31GR1E6 | 20596  | api-server | INFO     | werkzeug:_internal.py:97 | [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5001
 * Running on http://192.168.99.88:5001
2024-11-19T16:54:04.428497-+08:00 | DESKTOP-31GR1E6 | 20596  | api-server | INFO     | werkzeug:_internal.py:97 | [33mPress CTRL+C to quit[0m
2024-11-19T16:54:04.435654-+08:00 | DESKTOP-31GR1E6 | 20596  | api-server | INFO     | werkzeug:_internal.py:97 |  * Restarting with stat
2024-11-19T16:54:07.203746-+08:00 | DESKTOP-31GR1E6 | 22996  | api-server | WARNING  | werkzeug:_internal.py:97 |  * Debugger is active!
2024-11-19T16:54:07.220198-+08:00 | DESKTOP-31GR1E6 | 22996  | api-server | INFO     | werkzeug:_internal.py:97 |  * Debugger PIN: 272-859-533
2024-11-19T16:54:18.290714-+08:00 | DESKTOP-31GR1E6 | 19944  | api-server | INFO     | root:api_server.py:70 |  "/api/ai/scale/analyzer POST"
2024-11-19T16:54:18.291717-+08:00 | DESKTOP-31GR1E6 | 19944  | api-server | INFO     | root:api_server.py:16 | Í¼Æ¬µØÖ·: E:/electronic_scale/test3.png
2024-11-19T16:54:18.293549-+08:00 | DESKTOP-31GR1E6 | 19944  | api-server | ERROR    | root:api_server.py:26 | ²ÎÊý´íÎó: inference() got an unexpected keyword argument 'template_path'
Traceback (most recent call last):
  File "E:\electronic_scale\api_server.py", line 23, in post
TypeError: inference() got an unexpected keyword argument 'template_path'
2024-11-19T16:54:18.295562-+08:00 | DESKTOP-31GR1E6 | 19944  | api-server | INFO     | werkzeug:_internal.py:97 | 192.168.99.88 - - [19/Nov/2024 16:54:18] "[31m[1mPOST /api/ai/scale/analyzer HTTP/1.1[0m" 400 -
2024-11-19T16:54:33.475242-+08:00 | DESKTOP-31GR1E6 | 19944  | api-server | INFO     | root:api_server.py:70 |  "/api/ai/scale/analyzer POST"
2024-11-19T16:54:33.475242-+08:00 | DESKTOP-31GR1E6 | 19944  | api-server | INFO     | root:api_server.py:16 | Í¼Æ¬µØÖ·: E:/electronic_scale/test3.png
2024-11-19T16:54:33.475761-+08:00 | DESKTOP-31GR1E6 | 19944  | api-server | ERROR    | root:api_server.py:26 | ²ÎÊý´íÎó: inference() got an unexpected keyword argument 'template_path'
Traceback (most recent call last):
  File "E:\electronic_scale\api_server.py", line 23, in post
TypeError: inference() got an unexpected keyword argument 'template_path'
2024-11-19T16:54:33.476284-+08:00 | DESKTOP-31GR1E6 | 19944  | api-server | INFO     | werkzeug:_internal.py:97 | 192.168.99.88 - - [19/Nov/2024 16:54:33] "[31m[1mPOST /api/ai/scale/analyzer HTTP/1.1[0m" 400 -
2024-11-19T16:55:30.521173-+08:00 | DESKTOP-31GR1E6 | 19944  | api-server | INFO     | root:api_server.py:70 |  "/api/ai/scale/analyzer POST"
2024-11-19T16:55:30.522172-+08:00 | DESKTOP-31GR1E6 | 19944  | api-server | INFO     | root:api_server.py:16 | Í¼Æ¬µØÖ·: E:/electronic_scale/test3.png
2024-11-19T16:55:30.522172-+08:00 | DESKTOP-31GR1E6 | 19944  | api-server | ERROR    | root:api_server.py:26 | ²ÎÊý´íÎó: inference() got an unexpected keyword argument 'template_path'
Traceback (most recent call last):
  File "E:\electronic_scale\api_server.py", line 23, in post
TypeError: inference() got an unexpected keyword argument 'template_path'
2024-11-19T16:55:30.523171-+08:00 | DESKTOP-31GR1E6 | 19944  | api-server | INFO     | werkzeug:_internal.py:97 | 192.168.99.88 - - [19/Nov/2024 16:55:30] "[31m[1mPOST /api/ai/scale/analyzer HTTP/1.1[0m" 400 -
2024-11-19T16:55:31.448873-+08:00 | DESKTOP-31GR1E6 | 19944  | api-server | INFO     | root:api_server.py:70 |  "/api/ai/scale/analyzer POST"
2024-11-19T16:55:31.448873-+08:00 | DESKTOP-31GR1E6 | 19944  | api-server | INFO     | root:api_server.py:16 | Í¼Æ¬µØÖ·: E:/electronic_scale/test3.png
2024-11-19T16:55:31.448873-+08:00 | DESKTOP-31GR1E6 | 19944  | api-server | ERROR    | root:api_server.py:26 | ²ÎÊý´íÎó: inference() got an unexpected keyword argument 'template_path'
Traceback (most recent call last):
  File "E:\electronic_scale\api_server.py", line 23, in post
TypeError: inference() got an unexpected keyword argument 'template_path'
2024-11-19T16:55:31.449878-+08:00 | DESKTOP-31GR1E6 | 19944  | api-server | INFO     | werkzeug:_internal.py:97 | 192.168.99.88 - - [19/Nov/2024 16:55:31] "[31m[1mPOST /api/ai/scale/analyzer HTTP/1.1[0m" 400 -
2024-11-19T16:55:34.644803-+08:00 | DESKTOP-31GR1E6 | 19944  | api-server | INFO     | root:api_server.py:70 |  "/ POST"
2024-11-19T16:55:34.645807-+08:00 | DESKTOP-31GR1E6 | 19944  | api-server | INFO     | werkzeug:_internal.py:97 | 192.168.99.88 - - [19/Nov/2024 16:55:34] "[33mPOST / HTTP/1.1[0m" 404 -
2024-11-19T16:55:37.330188-+08:00 | DESKTOP-31GR1E6 | 19944  | api-server | INFO     | root:api_server.py:70 |  "/api/ai/scale/analyzer POST"
2024-11-19T16:55:37.330188-+08:00 | DESKTOP-31GR1E6 | 19944  | api-server | INFO     | root:api_server.py:16 | Í¼Æ¬µØÖ·: E:/electronic_scale/test3.png
2024-11-19T16:55:37.330188-+08:00 | DESKTOP-31GR1E6 | 19944  | api-server | ERROR    | root:api_server.py:26 | ²ÎÊý´íÎó: inference() got an unexpected keyword argument 'template_path'
Traceback (most recent call last):
  File "E:\electronic_scale\api_server.py", line 23, in post
TypeError: inference() got an unexpected keyword argument 'template_path'
2024-11-19T16:55:37.331194-+08:00 | DESKTOP-31GR1E6 | 19944  | api-server | INFO     | werkzeug:_internal.py:97 | 192.168.99.88 - - [19/Nov/2024 16:55:37] "[31m[1mPOST /api/ai/scale/analyzer HTTP/1.1[0m" 400 -
2024-11-19T16:57:16.845704-+08:00 | DESKTOP-31GR1E6 | 2064   | api-server | INFO     | werkzeug:_internal.py:97 | [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5001
 * Running on http://192.168.99.88:5001
2024-11-19T16:57:16.845704-+08:00 | DESKTOP-31GR1E6 | 2064   | api-server | INFO     | werkzeug:_internal.py:97 | [33mPress CTRL+C to quit[0m
2024-11-19T16:57:16.846701-+08:00 | DESKTOP-31GR1E6 | 2064   | api-server | INFO     | werkzeug:_internal.py:97 |  * Restarting with stat
2024-11-19T16:57:19.561669-+08:00 | DESKTOP-31GR1E6 | 22412  | api-server | WARNING  | werkzeug:_internal.py:97 |  * Debugger is active!
2024-11-19T16:57:19.564700-+08:00 | DESKTOP-31GR1E6 | 22412  | api-server | INFO     | werkzeug:_internal.py:97 |  * Debugger PIN: 272-859-533
2024-11-19T17:00:04.670100-+08:00 | DESKTOP-31GR1E6 | 22592  | api-server | INFO     | werkzeug:_internal.py:97 | [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5001
 * Running on http://192.168.99.88:5001
2024-11-19T17:00:04.670100-+08:00 | DESKTOP-31GR1E6 | 22592  | api-server | INFO     | werkzeug:_internal.py:97 | [33mPress CTRL+C to quit[0m
2024-11-19T17:00:15.460652-+08:00 | DESKTOP-31GR1E6 | 19944  | api-server | INFO     | root:api_server.py:70 |  "/api/ai/scale/analyzer POST"
2024-11-19T17:00:15.460652-+08:00 | DESKTOP-31GR1E6 | 19944  | api-server | INFO     | root:api_server.py:16 | Í¼Æ¬µØÖ·: E:/electronic_scale/test3.png
2024-11-19T17:00:15.460652-+08:00 | DESKTOP-31GR1E6 | 19944  | api-server | ERROR    | root:api_server.py:26 | ²ÎÊý´íÎó: inference() got an unexpected keyword argument 'template_path'
Traceback (most recent call last):
  File "E:\electronic_scale\api_server.py", line 23, in post
    encoded_url = quote(pict_url, safe=':/?&=')
TypeError: inference() got an unexpected keyword argument 'template_path'
2024-11-19T17:00:15.461649-+08:00 | DESKTOP-31GR1E6 | 19944  | api-server | INFO     | werkzeug:_internal.py:97 | 192.168.99.88 - - [19/Nov/2024 17:00:15] "[31m[1mPOST /api/ai/scale/analyzer HTTP/1.1[0m" 400 -
2024-11-19T17:00:17.594515-+08:00 | DESKTOP-31GR1E6 | 19944  | api-server | INFO     | root:api_server.py:70 |  "/api/ai/scale/analyzer POST"
2024-11-19T17:00:17.595517-+08:00 | DESKTOP-31GR1E6 | 19944  | api-server | INFO     | root:api_server.py:16 | Í¼Æ¬µØÖ·: E:/electronic_scale/test3.png
2024-11-19T17:00:17.595517-+08:00 | DESKTOP-31GR1E6 | 19944  | api-server | ERROR    | root:api_server.py:26 | ²ÎÊý´íÎó: inference() got an unexpected keyword argument 'template_path'
Traceback (most recent call last):
  File "E:\electronic_scale\api_server.py", line 23, in post
    encoded_url = quote(pict_url, safe=':/?&=')
TypeError: inference() got an unexpected keyword argument 'template_path'
2024-11-19T17:00:17.595517-+08:00 | DESKTOP-31GR1E6 | 19944  | api-server | INFO     | werkzeug:_internal.py:97 | 192.168.99.88 - - [19/Nov/2024 17:00:17] "[31m[1mPOST /api/ai/scale/analyzer HTTP/1.1[0m" 400 -
2024-11-19T17:01:12.406748-+08:00 | DESKTOP-31GR1E6 | 19944  | api-server | INFO     | root:api_server.py:70 |  "/api/ai/scale/analyzer POST"
2024-11-19T17:01:12.406748-+08:00 | DESKTOP-31GR1E6 | 19944  | api-server | INFO     | root:api_server.py:16 | Í¼Æ¬µØÖ·: E:/electronic_scale/test3.png
2024-11-19T17:01:12.407749-+08:00 | DESKTOP-31GR1E6 | 19944  | api-server | ERROR    | root:api_server.py:26 | ²ÎÊý´íÎó: inference() got an unexpected keyword argument 'template_path'
Traceback (most recent call last):
  File "E:\electronic_scale\api_server.py", line 23, in post
    encoded_url = quote(pict_url, safe=':/?&=')
TypeError: inference() got an unexpected keyword argument 'template_path'
2024-11-19T17:01:12.407749-+08:00 | DESKTOP-31GR1E6 | 19944  | api-server | INFO     | werkzeug:_internal.py:97 | 192.168.99.88 - - [19/Nov/2024 17:01:12] "[31m[1mPOST /api/ai/scale/analyzer HTTP/1.1[0m" 400 -
2024-11-19T17:04:47.671513-+08:00 | DESKTOP-31GR1E6 | 7796   | api-server | INFO     | werkzeug:_internal.py:97 | [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5001
 * Running on http://192.168.99.88:5001
2024-11-19T17:04:47.671513-+08:00 | DESKTOP-31GR1E6 | 7796   | api-server | INFO     | werkzeug:_internal.py:97 | [33mPress CTRL+C to quit[0m
2024-11-19T17:04:53.706006-+08:00 | DESKTOP-31GR1E6 | 19944  | api-server | INFO     | root:api_server.py:70 |  "/api/ai/scale/analyzer POST"
2024-11-19T17:04:53.707006-+08:00 | DESKTOP-31GR1E6 | 19944  | api-server | INFO     | root:api_server.py:16 | Í¼Æ¬µØÖ·: E:/electronic_scale/test3.png
2024-11-19T17:04:53.707006-+08:00 | DESKTOP-31GR1E6 | 19944  | api-server | ERROR    | root:api_server.py:26 | ²ÎÊý´íÎó: inference() got an unexpected keyword argument 'template_path'
Traceback (most recent call last):
  File "E:\electronic_scale\api_server.py", line 23, in post
    encoded_url = quote(pict_url, safe=':/?&=')
TypeError: inference() got an unexpected keyword argument 'template_path'
2024-11-19T17:04:53.708005-+08:00 | DESKTOP-31GR1E6 | 19944  | api-server | INFO     | werkzeug:_internal.py:97 | 192.168.99.88 - - [19/Nov/2024 17:04:53] "[31m[1mPOST /api/ai/scale/analyzer HTTP/1.1[0m" 400 -
2024-11-19T17:04:55.389517-+08:00 | DESKTOP-31GR1E6 | 19944  | api-server | INFO     | root:api_server.py:70 |  "/api/ai/scale/analyzer POST"
2024-11-19T17:04:55.390043-+08:00 | DESKTOP-31GR1E6 | 19944  | api-server | INFO     | root:api_server.py:16 | Í¼Æ¬µØÖ·: E:/electronic_scale/test3.png
2024-11-19T17:04:55.390043-+08:00 | DESKTOP-31GR1E6 | 19944  | api-server | ERROR    | root:api_server.py:26 | ²ÎÊý´íÎó: inference() got an unexpected keyword argument 'template_path'
Traceback (most recent call last):
  File "E:\electronic_scale\api_server.py", line 23, in post
    encoded_url = quote(pict_url, safe=':/?&=')
TypeError: inference() got an unexpected keyword argument 'template_path'
2024-11-19T17:04:55.390569-+08:00 | DESKTOP-31GR1E6 | 19944  | api-server | INFO     | werkzeug:_internal.py:97 | 192.168.99.88 - - [19/Nov/2024 17:04:55] "[31m[1mPOST /api/ai/scale/analyzer HTTP/1.1[0m" 400 -
2024-11-19T17:12:52.421605-+08:00 | DESKTOP-31GR1E6 | 19356  | api-server | INFO     | werkzeug:_internal.py:97 | [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5001
 * Running on http://192.168.99.88:5001
2024-11-19T17:12:52.446048-+08:00 | DESKTOP-31GR1E6 | 19356  | api-server | INFO     | werkzeug:_internal.py:97 | [33mPress CTRL+C to quit[0m
2024-11-19T17:13:48.782286-+08:00 | DESKTOP-31GR1E6 | 19356  | api-server | INFO     | root:api_server.py:78 |  "/api/ai/scale/analyzer POST"
2024-11-19T17:13:48.782286-+08:00 | DESKTOP-31GR1E6 | 19356  | api-server | INFO     | root:api_server.py:18 | Í¼Æ¬µØÖ·: E:/electronic_scale/test3.png
2024-11-19T17:13:48.792815-+08:00 | DESKTOP-31GR1E6 | 19356  | api-server | INFO     | root:api_server.py:65 | ½Ó¿Ú·µ»ØÖµÎª£º{'code': 200, 'result': None, 'msg': 'ÍÆÀí½á¹û²»ºÏ·¨'}
2024-11-19T17:13:48.793814-+08:00 | DESKTOP-31GR1E6 | 19356  | api-server | INFO     | root:api_server.py:66 | ½Ó¿ÚºÄÊ±: 0.00 Ãë
2024-11-19T17:13:48.793814-+08:00 | DESKTOP-31GR1E6 | 19356  | api-server | INFO     | werkzeug:_internal.py:97 | 192.168.99.88 - - [19/Nov/2024 17:13:48] "POST /api/ai/scale/analyzer HTTP/1.1" 200 -
2024-11-19T17:16:08.168878-+08:00 | DESKTOP-31GR1E6 | 12924  | api-server | INFO     | werkzeug:_internal.py:97 | [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5001
 * Running on http://192.168.99.88:5001
2024-11-19T17:16:08.168878-+08:00 | DESKTOP-31GR1E6 | 12924  | api-server | INFO     | werkzeug:_internal.py:97 | [33mPress CTRL+C to quit[0m
2024-11-19T17:16:11.021924-+08:00 | DESKTOP-31GR1E6 | 12924  | api-server | INFO     | root:api_server.py:79 |  "/api/ai/scale/analyzer POST"
2024-11-19T17:16:11.021924-+08:00 | DESKTOP-31GR1E6 | 12924  | api-server | INFO     | root:api_server.py:18 | Í¼Æ¬µØÖ·: E:/electronic_scale/test3.png
2024-11-19T17:16:11.022925-+08:00 | DESKTOP-31GR1E6 | 12924  | api-server | INFO     | root:api_server.py:66 | ½Ó¿Ú·µ»ØÖµÎª£º{'code': 200, 'result': None, 'msg': 'ÍÆÀí½á¹û²»ºÏ·¨'}
2024-11-19T17:16:11.022925-+08:00 | DESKTOP-31GR1E6 | 12924  | api-server | INFO     | root:api_server.py:67 | ½Ó¿ÚºÄÊ±: 0.00 Ãë
2024-11-19T17:16:11.023926-+08:00 | DESKTOP-31GR1E6 | 12924  | api-server | INFO     | werkzeug:_internal.py:97 | 192.168.99.88 - - [19/Nov/2024 17:16:11] "POST /api/ai/scale/analyzer HTTP/1.1" 200 -
2024-11-19T17:17:52.235867-+08:00 | DESKTOP-31GR1E6 | 15984  | api-server | INFO     | werkzeug:_internal.py:97 | [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5001
 * Running on http://192.168.99.88:5001
2024-11-19T17:17:52.235867-+08:00 | DESKTOP-31GR1E6 | 15984  | api-server | INFO     | werkzeug:_internal.py:97 | [33mPress CTRL+C to quit[0m
2024-11-19T17:18:22.858676-+08:00 | DESKTOP-31GR1E6 | 15376  | api-server | INFO     | werkzeug:_internal.py:97 | [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5001
 * Running on http://192.168.99.88:5001
2024-11-19T17:18:22.859704-+08:00 | DESKTOP-31GR1E6 | 15376  | api-server | INFO     | werkzeug:_internal.py:97 | [33mPress CTRL+C to quit[0m
2024-11-19T17:18:28.881315-+08:00 | DESKTOP-31GR1E6 | 15376  | api-server | INFO     | root:api_server.py:79 |  "/api/ai/scale/analyzer POST"
2024-11-19T17:18:28.882261-+08:00 | DESKTOP-31GR1E6 | 15376  | api-server | INFO     | root:api_server.py:18 | Í¼Æ¬µØÖ·: E:/electronic_scale/test3.png
2024-11-19T17:18:28.883260-+08:00 | DESKTOP-31GR1E6 | 15376  | api-server | INFO     | root:api_server.py:66 | ½Ó¿Ú·µ»ØÖµÎª£º{'code': 200, 'result': None, 'msg': 'ÍÆÀí½á¹û²»ºÏ·¨'}
2024-11-19T17:18:28.883260-+08:00 | DESKTOP-31GR1E6 | 15376  | api-server | INFO     | root:api_server.py:67 | ½Ó¿ÚºÄÊ±: 0.00 Ãë
2024-11-19T17:18:28.883260-+08:00 | DESKTOP-31GR1E6 | 15376  | api-server | INFO     | werkzeug:_internal.py:97 | 192.168.99.88 - - [19/Nov/2024 17:18:28] "POST /api/ai/scale/analyzer HTTP/1.1" 200 -
2024-11-19T17:21:20.005553-+08:00 | DESKTOP-31GR1E6 | 10384  | api-server | INFO     | werkzeug:_internal.py:97 | [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5001
 * Running on http://192.168.99.88:5001
2024-11-19T17:21:20.005553-+08:00 | DESKTOP-31GR1E6 | 10384  | api-server | INFO     | werkzeug:_internal.py:97 | [33mPress CTRL+C to quit[0m
2024-11-19T17:21:29.012448-+08:00 | DESKTOP-31GR1E6 | 10384  | api-server | INFO     | root:api_server.py:79 |  "/api/ai/scale/analyzer POST"
2024-11-19T17:21:29.012448-+08:00 | DESKTOP-31GR1E6 | 10384  | api-server | INFO     | root:api_server.py:18 | Í¼Æ¬µØÖ·: E:/electronic_scale/test3.png
2024-11-19T17:21:29.013446-+08:00 | DESKTOP-31GR1E6 | 10384  | api-server | INFO     | root:api_server.py:66 | ½Ó¿Ú·µ»ØÖµÎª£º{'code': 200, 'result': None, 'msg': 'ÍÆÀí½á¹û²»ºÏ·¨'}
2024-11-19T17:21:29.013446-+08:00 | DESKTOP-31GR1E6 | 10384  | api-server | INFO     | root:api_server.py:67 | ½Ó¿ÚºÄÊ±: 0.00 Ãë
2024-11-19T17:21:29.013446-+08:00 | DESKTOP-31GR1E6 | 10384  | api-server | INFO     | werkzeug:_internal.py:97 | 192.168.99.88 - - [19/Nov/2024 17:21:29] "POST /api/ai/scale/analyzer HTTP/1.1" 200 -
2024-11-19T17:22:33.956386-+08:00 | DESKTOP-31GR1E6 | 10384  | api-server | INFO     | root:api_server.py:79 |  "/api/ai/scale/analyzer POST"
2024-11-19T17:22:33.957384-+08:00 | DESKTOP-31GR1E6 | 10384  | api-server | INFO     | root:api_server.py:18 | Í¼Æ¬µØÖ·: http://192.168.100.3:7012/scione5/1854038721356238848-default/74122686336944d4abcb8e73d63e9300/1721123429.jpeg
2024-11-19T17:22:50.896441-+08:00 | DESKTOP-31GR1E6 | 10384  | api-server | INFO     | werkzeug:_internal.py:97 | 192.168.99.88 - - [19/Nov/2024 17:22:50] "POST /api/ai/scale/analyzer HTTP/1.1" 200 -
